;;; cargo-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cargo-mode.el

(autoload 'cargo-mode-execute-task "cargo-mode" "\
Select and execute cargo task.
If PREFIX is non-nil, prompt for additional params.

(fn &optional PREFIX)" t)
(autoload 'cargo-mode-test "cargo-mode" "\
Run the `cargo test` command.
If PREFIX is non-nil, prompt for additional params.

(fn &optional PREFIX)" t)
(autoload 'cargo-mode-build "cargo-mode" "\
Run the `cargo build` command.
If PREFIX is non-nil, prompt for additional params.

(fn &optional PREFIX)" t)
(autoload 'cargo-mode-clippy "cargo-mode" "\
Run the `cargo clippy` command.
If PREFIX is non-nil, prompt for additional params.

(fn &optional PREFIX)" t)
(autoload 'cargo-mode-test-current-buffer "cargo-mode" "\
Run the cargo test for the current buffer.
If PREFIX is non-nil, prompt for additional params.

(fn &optional PREFIX)" t)
(autoload 'cargo-mode-test-current-test "cargo-mode" "\
Run the Cargo test command for the current test.
If PREFIX is non-nil, prompt for additional params.

(fn &optional PREFIX)" t)
(autoload 'cargo-mode-last-command "cargo-mode" "\
Re-execute the last `cargo-mode` task." t)
(autoload 'cargo-minor-mode "cargo-mode" "\
Cargo minor mode.  Used for holding keybindings for `cargo-mode'.

\\{cargo-minor-mode-map}

This is a minor mode.  If called interactively, toggle the `cargo minor
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `cargo-minor-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "cargo-mode" '("cargo-"))

;;; End of scraped data

(provide 'cargo-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cargo-mode-autoloads.el ends here
